# signal_colors = {"H": "red", "VBF": "blue", "ttH": "lime"}


COLORS = [
    "#3f90da",
    "#ffa90e",
    "#bd1f01",
    "#94a4a2",
    "#832db6",
    "#a96b59",
    "#e76300",
    "#b9ac70",
    "#717581",
    "#92dadd",
]

ALL_BRANCHES = [
    "NJet",
    "Jet_Px",
    "Jet_Py",
    "Jet_Pz",
    "Jet_E",
    "Jet_btag",
    "Jet_ID",
    "NMuon",
    "Muon_Px",
    "Muon_Py",
    "Muon_Pz",
    "Muon_E",
    "Muon_Charge",
    "Muon_Iso",
    "NElectron",
    "Electron_Px",
    "Electron_Py",
    "Electron_Pz",
    "Electron_E",
    "Electron_Charge",
    "Electron_Iso",
    "NPhoton",
    "Photon_Px",
    "Photon_Py",
    "Photon_Pz",
    "Photon_E",
    "Photon_Iso",
    "MET_px",
    "MET_py",
    "MChadronicBottom_px",
    "MChadronicBottom_py",
    "MChadronicBottom_pz",
    "MCleptonicBottom_px",
    "MCleptonicBottom_py",
    "MCleptonicBottom_pz",
    "MChadronicWDecayQuark_px",
    "MChadronicWDecayQuark_py",
    "MChadronicWDecayQuark_pz",
    "MChadronicWDecayQuarkBar_px",
    "MChadronicWDecayQuarkBar_py",
    "MChadronicWDecayQuarkBar_pz",
    "MClepton_px",
    "MClepton_py",
    "MClepton_pz",
    "MCleptonPDGid",
    "MCneutrino_px",
    "MCneutrino_py",
    "MCneutrino_pz",
    "NPrimaryVertices",
    "triggerIsoMu24",
    "EventWeight",
]

N_BINS = {
    "NJet": 6,
    "Jet_Px": 50,
    "Jet_Py": 50,
    "Jet_Pz": 50,
    "Jet_E": 50,
    "Jet_btag": 50,
    "Jet_ID": 2,
    "NMuon": 6,
    "Muon_Px": 50,
    "Muon_Py": 50,
    "Muon_Pz": 50,
    "Muon_E": 50,
    "Muon_Charge": 3,
    "Muon_Iso": 50,
    "NElectron": 3,
    "Electron_Px": 50,
    "Electron_Py": 50,
    "Electron_Pz": 50,
    "Electron_E": 50,
    "Electron_Charge": 3,
    "Electron_Iso": 50,
    "NPhoton": 3,
    "Photon_Px": 50,
    "Photon_Py": 50,
    "Photon_Pz": 50,
    "Photon_E": 50,
    "Photon_Iso": 50,
    "MET_px": 50,
    "MET_py": 50,
    "MChadronicBottom_px": 50,
    "MChadronicBottom_py": 50,
    "MChadronicBottom_pz": 50,
    "MCleptonicBottom_px": 50,
    "MCleptonicBottom_py": 50,
    "MCleptonicBottom_pz": 50,
    "MChadronicWDecayQuark_px": 50,
    "MChadronicWDecayQuark_py": 50,
    "MChadronicWDecayQuark_pz": 50,
    "MChadronicWDecayQuarkBar_px": 50,
    "MChadronicWDecayQuarkBar_py": 50,
    "MChadronicWDecayQuarkBar_pz": 50,
    "MClepton_px": 50,
    "MClepton_py": 50,
    "MClepton_pz": 50,
    "MCleptonPDGid": 50,
    "MCneutrino_px": 50,
    "MCneutrino_py": 50,
    "MCneutrino_pz": 50,
    "NPrimaryVertices": 50,
    "triggerIsoMu24": 3,
    "EventWeight": 50,
}

X_RANGE = {
    "NJet": (0, 6),
    "Jet_Px": (-220, 220),
    "Jet_Py": (-220, 220),
    "Jet_Pz": (-500, 500),
    "Jet_E": (0, 700),
    "Jet_btag": (-1, 6),
    "Jet_ID": (0, 2),
    "NMuon": (0, 6),
    "Muon_Px": (-150, 150),
    "Muon_Py": (-150, 150),
    "Muon_Pz": (-350, 350),
    "Muon_E": (0, 350),
    "Muon_Charge": (-1, 2),
    "Muon_Iso": (-0, 7),
    "NElectron": (0, 3),
    "Electron_Px": (-150, 150),
    "Electron_Py": (-150, 150),
    "Electron_Pz": (-250, 250),
    "Electron_E": (0, 500),
    "Electron_Charge": (-1, 2),
    "Electron_Iso": (0, 10),
    "NPhoton": (0, 3),
    "Photon_Px": (-120, 120),
    "Photon_Py": (-120, 120),
    "Photon_Pz": (-320, 320),
    "Photon_E": (0, 500),
    "Photon_Iso": (-10, 50),
    "MET_px": (-150, 150),
    "MET_py": (-150, 150),
    "MChadronicBottom_px": (-400, 400),
    "MChadronicBottom_py": (-400, 400),
    "MChadronicBottom_pz": (-400, 400),
    "MCleptonicBottom_px": (-400, 400),
    "MCleptonicBottom_py": (-400, 400),
    "MCleptonicBottom_pz": (-400, 400),
    "MChadronicWDecayQuark_px": (-400, 400),
    "MChadronicWDecayQuark_py": (-400, 400),
    "MChadronicWDecayQuark_pz": (-400, 400),
    "MChadronicWDecayQuarkBar_px": (-400, 400),
    "MChadronicWDecayQuarkBar_py": (-400, 400),
    "MChadronicWDecayQuarkBar_pz": (-400, 400),
    "MClepton_px": (-400, 400),
    "MClepton_py": (-400, 400),
    "MClepton_pz": (-400, 400),
    "MCleptonPDGid": (-400, 400),
    "MCneutrino_px": (-400, 400),
    "MCneutrino_py": (-400, 400),
    "MCneutrino_pz": (-400, 400),
    "NPrimaryVertices": (0, 50),
    "triggerIsoMu24": (0, 3),
    "EventWeight": (-0, 10),
}


BACKGROUND_SOURCES = ["dy", "qcd", "wjets", "single_top", "ww", "wz", "zz"]
SIGNAL_SOURCES = ["ttbar"]
SOURCES_LABEL = {
    "qcd": r"QCD",
    "wjets": r"$W$+jets",
    "single_top": r"Single top",
    "dy": r"DY",
    "ww": r"$WW$",
    "wz": r"$WZ$",
    "zz": r"$ZZ$",
    "ttbar": r"$t\bar{t}$",
    "data": r"data",
}
